services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: proposals
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
